modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="ecologicmagic"
version="${file.jarVersion}"
displayName="EcologicMagic"
description='''

'''
[[dependencies.egologicmagic]]
   modId="forge" 
   mandatory=true
   versionRange="[36,)"

[[dependencies.egologicmagic]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   
[[dependencies.egologicmagic]]
   modId="curios"
   mandatory=false
   versionRange="[1.16.5-4.0.5.2,)"

